### ISSUE TITLE
Stylesheets cannot be used from the CDN

### ISSUE THREAD

**Issue by Boobies** [docbook/cdn#19]
I believe there is an issue with the DocBook CDN, but I am not sure precisely what it is. Try using the stylesheets directly from the CDN. Note that the old SourceForge links do not produce these errors.

xsltproc's complaint:

>error : Unknown IO error
>warning: failed to load external entity "http://cdn.docbook.org/release/xsl/current/manpages/docbook.xsl"
>cannot parse http://cdn.docbook.org/release/xsl/current/manpages/docbook.xsl`

Saxon 6's complaint:

>Error on line 1 column 1 of http://cdn.docbook.org/release/xsl/manpages/docbook.xsl:
>  Error reported by XML parser: Content is not allowed in prolog.
>Transformation failed: Failed to parse stylesheet`

**Comment by ndw** [comment]
Try https:// 

I think what's happening is http:// is returning a redirect, perhaps with an HTML page, and that's not XML.
