### ISSUE TITLE
CDN missing bibliography.xml file (and the whole dir)

### ISSUE THREAD

**Issue by eduardtibet** [docbook/cdn#8]
Docbook XSL Stylesheets (recent version), file ``param.xsl`` points to ``bibliography.xml`` file that is missing at CDN.

```
<xsl:param name="bibliography.collection">http://cdn.docbook.org/release/xsl/bibliography/bibliography.xml</xsl:param>
```

From URL it is clear visible that the whole bibliography dir is missing.
Linked back this issue directly to docbook stylesheets project https://github.com/docbook/xslt10-stylesheets/issues/84

**Comment by ndw** [comment]
I propose that that link should be changed to

    resources/latest/xml/bibliography.xml

I bet there's a corresponding glossary link that should be updated as well.

**Comment by eduardtibet** [comment]
Now bibliography sample file `bibliography.xml` is located at https://cdn.docbook.org/resources/latest/xml/bibliography.xml
Same for `glossary.xml`: https://cdn.docbook.org/resources/latest/xml/glossary.xml

Paths fixed within DocBook XSL Stylesheets current master branch.
